apiVersion: v1
kind: Secret
metadata:
  name: rtsp-config
type: Opaque
stringData:
  # --- REQUIRED: Replace these with your actual Azure credentials ---
  AZURE_VISION_SUBSCRIPTION_KEY: "YOUR_AZURE_KEY_HERE"
  AZURE_VISION_ENDPOINT: "https://your-endpoint.cognitiveservices.azure.com/"
  RTSP_URL: "rtsp://your-stream-url-here"
  
  # --- NEW: InfluxDB Connection Details (MUST MATCH k8s-influxdb.yaml) ---
  INFLUXDB_URL: "http://influxdb-service:8086"
  INFLUXDB_TOKEN: "YOUR_INFLUXDB_TOKEN" # !!! REPLACE THIS WITH YOUR SECURE TOKEN !!!
  INFLUXDB_ORG: "rtsp-project-org"
  INFLUXDB_BUCKET: "analysis_data"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-object-detector
  labels:
    app: rtsp-object-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp-object-detector
  template:
    metadata:
      labels:
        app: rtsp-object-detector
    spec:
      volumes:
        # Volume for inter-container communication (Shared Memory replacement)
        - name: shm-volume
          emptyDir:
            medium: Memory # Use RAM for speed
            sizeLimit: 10Mi # Limit memory usage
      containers:
        # 1. Web Application Container
        - name: web-app
          image: your-registry/rtsp-object-detector:latest # !!! REPLACE WITH YOUR IMAGE PATH !!!
          command: ["gunicorn", "-b", "0.0.0.0:8000", "-k", "gevent", "app:app"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shm-volume
              mountPath: /dev/shm # Mount the emptyDir as the shared memory location
          envFrom:
            - secretRef:
                name: rtsp-config
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"

        # 2. Camera Manager Container
        - name: camera-manager
          image: your-registry/rtsp-object-detector:latest # !!! REPLACE WITH YOUR IMAGE PATH !!!
          command: ["python3", "camera_manager.py"]
          volumeMounts:
            - name: shm-volume
              mountPath: /dev/shm # Mount the emptyDir as the shared memory location
          envFrom:
            - secretRef:
                name: rtsp-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rtsp-object-detector-service
spec:
  selector:
    app: rtsp-object-detector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rtsp-detector-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: rtsp-detector.your-domain.com # !!! REPLACE THIS WITH YOUR HOSTNAME !!!
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rtsp-object-detector-service
            port:
              number: 80
